### ISSUE TITLE
Freedrive mode not working?

### ISSUE THREAD

**Issue by broofa** [SintefRaufossManufacturing/python-urx#11]
Hi, I'm working with a UR5, trying to put it into freedrive mode.  URRobot.set_freedrive(True) does not seem to be working.  Reading the urx code it looks like it's sending `set robotmode freedrive`, however in reading the v3.2 of the URScript Programming Language guide, I don't see any mention of a `robotmode` command.  Am I missing something?

(Note: I'm new to this so my apologies if I'm overlooking something obvious.)

Cc: @markwsilliman

**Comment by oroulet** [comment]
It used to work..., We'll check

**Comment by zchen24** [comment]
In my lab, there are one UR3 running 3.1 and one UR5 running 1.8. This "set robotmode freedrive" command works on UR5, but does not work on UR3.

**Comment by markwsilliman** [comment]
We're using this on a UR5 now that is running 3.4 so I would expect 3.1 to work.  One trick that we had to do is create a script to sleep after enabling freedrive.  Otherwise the program ends and freedrive turns off (all in < 1 second). 

Check your logs (on the robot) to see if the freemode is turning on and off.  If yes adding the sleep will fix it.

**Comment by zchen24** [comment]
@markwsilliman Could you elaborate on "create a script to sleep after enabling freedrive"? 
On UR3, I also tried to call ```freedrive_mode()``` and found that the UR turns freedrive mode on, then turns it off after 16 ms.

**Comment by markwsilliman** [comment]
Try something like:

 with urx.Robot(robot_ip) as rob:
            rob.send_program(b"def myProg():\n\tfreedrive_mode()\nsleep({})\nend".format(timeout))

**Comment by zchen24** [comment]
WOW, works like a charm. Thank you!
